app: companies-rest-api
service: companies-rest-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:204894123339:table/ml-companies"

functions:
  getCompanies:
    handler: handler.getCompanies
    events:
      - http:
          path: /companies
          method: get
          cors:
            origin: "https://*.amazonaws.com"
            headers: "*"
  addCompany:
    handler: handler.addCompany
    events:
      - http:
          path: /companies
          method: post
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              application/x-www-form-urlencoded: null
              application/json: null
          cors:
            origin: "https://*.amazonaws.com"
            headers: "*"
  updateCompany:
    handler: handler.updateCompany
    events:
      - http:
          path: /companies
          method: patch
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              application/x-www-form-urlencoded: null
              application/json: null
          cors:
            origin: "https://*.amazonaws.com"
            headers: "*"
  deleteCompany:
    handler: handler.deleteCompany
    events:
      - http:
          path: /companies
          method: delete
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              application/x-www-form-urlencoded: null
              application/json: null
          cors:
            origin: "https://*.amazonaws.com"
            headers: "*"
